export const ATTRIBUTES = {
  "ASEG Continuation Full Time Equivalent": "GCON-FTCON",
  "ASEG Continuation Part Time Equivalent": "GCON-PTCON",
  "Occupational Therapy Level II Fieldwork-Full Time": "GOFW-FTOTFWORK",
  "Graduate Research Assistantship": "GAST-GRADRA",
  "Graduate Teaching Assistantship": "GAST-GRADTA",
  "DMD/MPH Required Courses": "PDMD-REQUIRED",
  "DVM/MPH Elective Courses": "PDVM-ELECTIVE",
  "DVM/MPH Required Courses": "PDVM-REQUIRED",
  "DrPH Required Courses": "PDRP-REQUIRED",
  "SoE-Computing": "ENDS-COMPUTING",
  "SoE-Engineering": "ENDS-ENGINEERC",
  "SoE-HASS": "ENDS-SOE-HASS",
  "SoE-HASS-Arts": "ENDS-ARTS",
  "SoE-HASS-Humanities": "ENDS-HUMANITIES",
  "SoE-HASS-Social Sciences": "ENDS-SOCIALSCI",
  "SoE-Mathematics": "ENDS-MATHSCIEN",
  "SoE-Natural Sciences": "ENDS-NATURALSCI",
  "Epidemiology/Biostatistics Elective Courses": "PEBO-ELECTIVE",
  "Epidemiology/Biostatistics Required Courses": "PEBO-REQUIRED",
  "Fletcher PhD Students Only": "FPHD-FPHD",
  "GSBS Continuation Full Time Equivalent": "SCON-FTCON",
  "Generalist Required Courses": "PGEN-REQUIRED",
  "Global Health Required Courses": "PGH-REQUIRED",
  "MFA Studio Art": "ASEG-MFASTUD",
  "MPH-HCOM Elective Courses": "PMHC-ELECTIVE",
  "MPH-HCOM Required Courses": "PMHC-REQUIRED",
  "Health Services Mgmt & Policy Elective Courses": "PHSM-ELECTIVE",
  "Health Services Mgmt & Policy Required Courses": "PHSM-REQUIRED",
  "JD/MPH Required Courses": "PJD-REQUIRED",
  "College Writing I": "LACW-CWI",
  "College Writing II": "LACW-CWII",
  "Foreign Language Level 22+": "LAFL-FL22+",
  "Foreign Language Level 3+": "LAFL-FL3+",
  "BFA-Art History": "LADS-BFAARTHIST",
  "BFA-Studio Art": "LADS-BFASTUD",
  "BFA-Humanities": "LADS-BFAHUM",
  "BFA-Language/Culture": "LADS-BFALAN/CUL",
  "BFA-Science/Technology": "LADS-BFASCI/TCH",
  "BFA-Social Science": "LADS-BFASOCSCI",
  "LA-Distribution-Arts": "LADS-ARTS",
  "LA-Distribution-Humanities": "LADS-HUMANITIES",
  "LA-Distribution-Mathematics": "LADS-MATHSCIEN",
  "LA-Distribution-Natural Sciences": "LADS-NATURALSCI",
  "LA-Distribution-Social Sciences": "LADS-SOCIALSCI",
  "World Civilization Requirement": "LAFD-WORLDCIV",
  "African Cult/Lang-Diasporas": "LACL-AFRICAN",
  "African Cult/Lang-Reg Origin": "LACL-REGAFRICA",
  "Classical Culture/Language": "LACL-CLASSICAL",
  "East Asian Cult/Lang-Diasporas": "LACL-EASTASIAN",
  "East Asian Cult/Lang-Reg Origin": "LACL-REGEASIA",
  "French Culture/Language": "LACL-FRENCH",
  "Germanic Culture/Language": "LACL-GERMANIC",
  "Hispanic Cult/Lang-Diasporas": "LACL-HISPANIC",
  "Hispanic Cult/Lang-Reg Origin": "LACL-REGHISPAN",
  "Italian Culture/Language": "LACL-ITALIAN",
  "Judaic Culture/Language": "LACL-JUDAIC",
  "Middle Eastern Culture/Language": "LACL-MIDDLEEAST",
  "Native American Culture": "LACL-NATIVEAMER",
  "Russian Culture/Language": "LACL-RUSSIAN",
  "S/SoE Asia Culture/Lang-Reg Origin": "LACL-REGSEASIA",
  "Sign Language/Deaf Culture": "LACL-SIGNLANG",
  "South/Southeast Asia Cult/Lang": "LACL-SOUTHASIA",
  "MD/MPH Required Courses": "PMDM-REQUIRED",
  "MBS Elective Courses": "PMBS-ELECTIVE",
  "MS HIA Elective Courses": "PHIA-ELECTIVE",
  "MS HIA Required Courses": "PHIA-REQUIRED",
  "MS-Health Communication": "PHCO-ELECTIVE",
  "MPH General Elective Courses": "PMPH-ELECTIVE",
  "MPH Required Courses": "PMPH-REQUIRED",
  "New Course This Semester": "ANEW-NEW",
  "Nutrition Full-Time Continuation": "NCON-NCONFT",
  "Full-Time Equivalent": "PXTE-FT",
  "Half-Time Equivalent": "PXTE-HT",
  "Studio Art": "STUD-STUD",
};
