/*
 * Course attributes
 */

export const ATTRIBUTES = [
  "BFA-Language/Culture",
  "BFA-Social Science",
  "LA-Distribution-Social Sciences",
  "SoE-HASS",
  "SoE-HASS-Social Sciences",
  "World Civilization Requirement",
  "",
  "BFA-Humanities",
  "East Asian Cult/Lang-Diasporas",
  "LA-Distribution-Humanities",
  "SoE-HASS-Humanities",
  "East Asian Cult/Lang-Reg Orign",
  "African Cult/Lang - Diasporas",
  "African Cult/Lang-Reg Origin",
  "LA-Distribution-Arts",
  "SoE-HASS-Arts",
  "SoE-Engineering",
  "Hispanic Cult/Lang - Diasporas",
  "Russian Culture/Language",
  "BFA-Science/Technology",
  "LA-Distribution-Natural Sciences",
  "Native American Culture",
  "Hispanic Cult/Lang-Region Orig",
  "First Class in Multi Sequence",
  "Foreign Language Level 3+",
  "Middle Eastern Cult/Lang",
  "Judaic Culture/Language",
  "Foreign Language Level 22+",
  "Classical Culture/Language",
  "SoE-Natural Sciences",
  "LA-Distribution-Mathematics",
  "Part Time Equivalent",
  "Full Time Equivalent",
  "Graduate Teaching Assistantship",
  "Graduate Research Assistantship",
  "SoE-Mathematics",
  "BFA Studio Art",
  "MFA Studio Art",
  "Studio Art",
  "Italian Culture/Language",
  "Full-Time Equivalent",
  "MD/MPH Required Courses",
  "DVM/MPH Required Courses",
  "DVM/MPH Elective Courses",
  "SOE-Computing",
  "Sign Language/Deaf Culture",
  "S/SoE Asia Cult/Lang-Reg Orign",
  "South/Southeast Asia Cult/Lang",
  "New Course This Semester",
  "College Writing I",
  "College Writing II",
  "BFA Art History",
  "Combined Degree with The Museum School",
  "French Culture/Language",
  "Germanic Culture/Language",
  "MS HIA Required Courses",
  "MPH General Elective Courses",
  "MS HIA Elective Courses",
  "Half-Time Equivalent",
  "Course is for Fletcher PhD students only.",
  "Nutrition Full-Time Continuation",
  "Occupational Therapy Level II Fieldwork- Full Time",
  "MBS Elective Courses",
  "MPH Required Courses",
  "Epidemiology/Biostatistics Required Courses",
  "DrPH Required Courses",
  "Health Services Mgmt & Policy Required Courses",
  "MS-Health Communication",
  "Global Health Required Courses",
  "DMD/MPH Required Courses",
  "Epidemiology/Biostatistics Elective Courses",
  "Generalist Required Courses",
  "Health Services Mgmt & Policy Elective Courses",
  "JD/MPH Required Courses",
  "MPH-HCOM Elective Courses",
  "MPH-HCOM Required Courses",
];
