/*
 * @Asian American Studies = AAST,
 * @All College = ACL,
 * @Africana Studies = AFR,
 * @American Studies = AMER,
 * @Anthropology = ANTH,
 * @Arabic = ARB,
 * @Archaeology = ARCH,
 * @Astronomy = AST,
 * @Biochemistry = BCHM,
 * @Biology = BIO,
 * @Bioengineering = BIOE,
 * @Biomedical Engineering = BME,
 * @Civil & Environmental Eng = CEE,
 * @Ceramics = CER,
 * @Community Health = CH,
 * @Chemical & Biological Eng = CHBE,
 * @Chemistry = CHEM,
 * @Chinese = CHNS,
 * @Ctr for Interdis Studies = CIS,
 * @Classics = CLS,
 * @Cell, Molecular & Dev Biology = CMDB,
 * @MD/DVM/Public Health = CMPH,
 * @Computer Science = CS,
 * @Child Study&Human Development = CSHD,
 * @Colonialism Studies = CST,
 * @Clinical & Translational Sci = CTS,
 * @Civic Studies = CVS,
 * @Data Analytics = DATA,
 * @Advanced & Graduate Education = DEGR,
 * @Diversity,Equity,Inclusion&Jus = DEIJ,
 * @Diplomacy, History & Politics = DHP,
 * @Digital Media = DIG,
 * @Dance = DNC,
 * @Drawing = DRW,
 * @Drawing Medford = DRWM,
 * @Data Science = DS,
 * @Economics = EC,
 * @Earth and Climate Sciences = ECS,
 * @Education = ED,
 * @Education at Museum School = EDS,
 * @Electrical & Computer Eng = EE,
 * @Economics & Intl Business = EIB,
 * @Engineering Management = EM,
 * @Engineering, Introductory = EN,
 * @Engineering Education = ENE,
 * @English = ENG,
 * @English (Museum) = ENGS,
 * @Engineering Psychology = ENP,
 * @Entrepreneurship = ENT,
 * @Environmental Studies = ENV,
 * @Engineering Science = ES,
 * @Experimental College = EXP,
 * @History of Art = FAH,
 * @Fibers = FIB,
 * @Film and Media Studies = FMS,
 * @French = FR,
 * @BioMed Cross Reg = GBCR,
 * @BioMed MD/PhD = GBMD,
 * @Genetics = GENE,
 * @German = GER,
 * @Geographic Information Systems = GIS,
 * @Graphic Arts = GRA,
 * @Greek = GRK,
 * @BioMed Wide Courses = GSBS,
 * @Hebrew = HEB,
 * @Health Informatics & Analytics = HIA,
 * @History = HIST,
 * @Interdisciplinary = IDIS,
 * @Intr Literary & Cultural Study = ILCS,
 * @Intl Law and Organizations = ILO,
 * @Intern.Literary&Visual Studies = ILVS,
 * @Immunology = IMM,
 * @International Relations = IR,
 * @Integrated Studies Program = ISP,
 * @Italian = ITAL,
 * @Japanese = JPN,
 * @Judaic Studies = JS,
 * @Latin American Studies = LAS,
 * @Latin = LAT,
 * @Linguistics = LING,
 * @Latino Studies = LST,
 * @Mathematics = MATH,
 * @Media Arts = MDIA,
 * @Medieval Studies = MDVL,
 * @Mechanical Engineering = ME,
 * @Middle Eastern Studies = MES,
 * @Modern Language = ML,
 * @Molecular Microbiology = MMB,
 * @Materials Science Engineering = MSE,
 * @Metals = MTL,
 * @Music = MUS,
 * @Neuroscience = NRSC,
 * @Nutrition Undergraduate = NU,
 * @Nutrition Blended Program = NUTB,
 * @Nutrition Certificate = NUTC,
 * @Nutrition = NUTR,
 * @Occupational Therapy = OTS,
 * @Painting = PAI,
 * @Painting Medford = PAIM,
 * @Physical Education = PE,
 * @Performance = PER,
 * @Public Health = PH,
 * @Philosophy = PHIL,
 * @Photography = PHT,
 * @Photography Medford = PHTM,
 * @Physics = PHY,
 * @Portuguese = POR,
 * @Pharm & Exper Therapeutics = PPET,
 * @Print and Paper = PRT,
 * @Political Science = PS,
 * @Psychology = PSY,
 * @Race, Colonialism and Diaspora = RCD,
 * @Religion = REL,
 * @Russian = RUS,
 * @Sculpture = SCP,
 * @School of Museum of Fine Arts = SMFA,
 * @Sociology = SOC,
 * @Spanish = SPN,
 * @Sci, Tech, and Society = STS,
 * @The Gordon Institute = TGI,
 * @Theatre & Performance Studies = TPS,
 * @Open Enrollment = UCOE,
 * @Urban & Env Policy & Planning = UEP,
 * @Visual and Material Studies = VMS,
 * @Women's, Gender, and Sexuality = WGSS
 */

export const SUBJECTS = [
  "AAST",
  "ACL",
  "AFR",
  "AMER",
  "ANTH",
  "ARB",
  "ARCH",
  "AST",
  "BCHM",
  "BIO",
  "BIOE",
  "BME",
  "CEE",
  "CER",
  "CH",
  "CHBE",
  "CHEM",
  "CHNS",
  "CIS",
  "CLS",
  "CMDB",
  "CMPH",
  "CS",
  "CSHD",
  "CST",
  "CTS",
  "CVS",
  "DATA",
  "DEGR",
  "DEIJ",
  "DHP",
  "DIG",
  "DNC",
  "DRW",
  "DRWM",
  "DS",
  "EC",
  "ECS",
  "ED",
  "EDS",
  "EE",
  "EIB",
  "EM",
  "EN",
  "ENE",
  "ENG",
  "ENGS",
  "ENP",
  "ENT",
  "ENV",
  "ES",
  "EXP",
  "FAH",
  "FIB",
  "FMS",
  "FR",
  "GBCR",
  "GBMD",
  "GENE",
  "GER",
  "GIS",
  "GRA",
  "GRK",
  "GSBS",
  "HEB",
  "HIA",
  "HIST",
  "IDIS",
  "ILCS",
  "ILO",
  "ILVS",
  "IMM",
  "INTR",
  "IR",
  "ISP",
  "ITAL",
  "JPN",
  "JS",
  "LAS",
  "LAT",
  "LING",
  "LST",
  "MATH",
  "MDIA",
  "MDVL",
  "ME",
  "MES",
  "ML",
  "MMB",
  "MSE",
  "MTL",
  "MUS",
  "NRSC",
  "NU",
  "NUTB",
  "NUTC",
  "NUTR",
  "OTS",
  "PAI",
  "PAIM",
  "PE",
  "PER",
  "PH",
  "PHIL",
  "PHT",
  "PHTM",
  "PHY",
  "POR",
  "PPET",
  "PRT",
  "PS",
  "PSY",
  "RCD",
  "REL",
  "RUS",
  "SCP",
  "SMFA",
  "SOC",
  "SPN",
  "STS",
  "TGI",
  "TPS",
  "UCOE",
  "UEP",
  "VMS",
  "WGSS",
] as const;
