// export const SUBJECTS = {
//   "Asian American Studies": "AAST",
//   "All College": "ACL",
//   "Africana Studies": "AFR",
//   "American Studies": "AMER",
//   Anthropology: "ANTH",
//   Arabic: "ARB",
//   Archaeology: "ARCH",
//   Astronomy: "AST",
//   Biochemistry: "BHCM",
//   Biology: "BIO",
//   Bioengineering: "BIOE",
//   "Biomedical Engineering": "BME",
//   "Civil & Environmental Eng": "CEE",
//   Ceramics: "CER",
//   "Community Health": "CH",
//   "Chemical & Biological Eng": "CHBE",
//   Chemistry: "CHEM",
//   Chinese: "CHNS",
//   "Ctr for Interdis Studies": "CIS",
//   Classics: "CLS",
//   "Cell, Molecular & Dev Biology": "CMDB",
//   "MD/DVM/Public Health": "CMPH",
//   "Computer Science": "CS",
//   "Child Study&Human Development": "CSHD",
//   "Colonialism Studies": "CST",
//   "Clinical & Translational Sci": "CTS",
//   "Civic Studies": "CVS",
//   "Data Analytics": "DATA",

// };
